### ISSUE TITLE
Porting to BSD, questions

### ISSUE THREAD

**Issue by forquare** [msmhq/msm#289]
I’ve forked MSM with the plan to start to port it to BSD (which probably means making various commands more POSIX compliant), this should also make it easier to port to OS X at some point in the future.

I wondered if I might ask as to why values from `/etc/msm.conf` are read in as they are in the `manager_property()` function as apposed to doing something like `source $CONF`?
I only ask as I’ve spent a good number of hours trying to make the `sed` command on line 2021 to work on BSD, and I’ve finally given up and exploring other options…

The only advantage, that I can see, of using the `manager_property()` function is that you also get to create a `LOADED_` variable with a boolean value stating whether the variable has been loaded or not, and this allows you to load it only once and check for it being loaded elsewhere.  
I’m not sure how useful this is—I would usually check to see if a variable was set (e.g. `if [[ -z $var ]]`).

I hadn’t anticipated `msm` being quite so long!  And at the moment I’ve been mainly concentrating on replacing syntax that doesn’t alter the expected output, so I currently don’t have a great “bigger picture” of the codebase, nor do I have much of an idea about the conventions and mechanisms used within it.

**Comment by MiGeHo** [comment]
Are you talking about `sed -rn "s/^$1=('|\"|)(.*)\1/\2/ip" "$CONF"`? It just searches the config file $CONF for any occurrence of the property given to `manager_property()` and removes the left-hand symbol, the = sign, and any quotes around the value. So something like `msm-version="minecraft/1.3.0"` will be returned as `minecraft/1.3.0`.

I guess one of the reasons why those files are not just source'd is because they could pollute the namespace of the msm script and/or have stuff in them that goes beyond just setting variables. The only files source'd are the version scripts (like 1.3.0.sh).
