### ISSUE TITLE
MSM version

### ISSUE THREAD

**Issue by endofcake** [msmhq/msm#300]
Two questions about the versioning of MSM:

- is there a way to check the version of the currently installed MSM? Tried something like `msm -v` and `msm --version`, also skimmed through `msm help` -- no luck.
- should the instructions on http://msmhq.com/ be updated to mention v 0.9? Also, how do we update the docs for MSM?

@marcuswhybrow

**Comment by endofcake** [comment]
Found the answer to the first one -- didn't expect it to be `msm version`, something like `msm -v` seems a bit more idiomatic.

**Comment by marcuswhybrow** [comment]
* I can't remember why I decided to stick with `version` instead of `--version` or `-v`. You're right, the later is what people expect.
* The docs should be updated yes: http://msmhq.com is a Jekyll site in the [gh-pages branch][gh-pages] which we should all have write access to.

[gh-pages]: https://github.com/msmhq/msm/tree/gh-pages

**Comment by endofcake** [comment]
Cheers, now I know where to look!
