### ISSUE TITLE
Can't get Feed the Beast to work on MSM

### ISSUE THREAD

**Issue by rbremer** [msmhq/msm#318]
I have successfully installed MSM on Ubuntu 14.04 server.
Creating new servers with vanilla minecraft is no problem and works fine.

But i am failing to have a feed the beast server running. 
The problem also is, that the server download is zipped and not available as a single jar file.

I also tried to download the FTB server software and have the jar file replaced with the ftb jar file.

Is there a tutorial or documentation how to config other minecraft server other then vanilla?

**Comment by kjkazinski** [comment]
Hi Ruud,
Sorry for the late response.  

You need to point the link to the FTB jar file and not the minecraft jar file.
Hope that helps.

**Comment by rbremer** [comment]
@kjkazinski 
I have managed to get the server up and running. However, i was not able to do it via a jargroup. For some reason it doesn't start the server if the FTBserver jar file is a link.
I copied the ftb server jar file into the msm server directory and renamed it server.jar
This way the server does start (takes a long time even though the script says "server started").

Is there a reason why the linked version with a jar group doesn't work?

**Comment by kjkazinski** [comment]
Ruud,
The first time the server starts up it has to create the world, so this is why it may take a long time.
Does it always take a long time to start, even after the second time you start it?

**Comment by rbremer** [comment]
@kjkazinski

To run FTB infinity evolved, I first have to run it without msm. This way everything is set up to run with all the mods installed (about 175).
Then I copy the content of the directory into the msm server directory.
I move the world directory into the worldstorage directory.

i have copied the ftbinfinity server jar file to its own apache html directory and made a jar group of it.
This will set the correct server jar file.
However when i start the server with the msm command, it doesn't come up.
When i unlink the server.jar and copy the ftbinfinity server jar file and rename it to server.jar, it will run.

**Comment by Kadah** [comment]
I think this is how I did my non-vanilla servers:
Make a new folder under servers.
Install the server to there via what ever means it requires for its normal Linux setup and run it once manually then stop after its online.
(Optional) Make a dummy jargroup and assign it to that server.
Add msm-jar-path=file_name_for_server_jar_here.jar to server.properties, also set msm-ram there if needed.
Make worldstorage folder, move server's world folder there.

You should now be able to do msm server_name start

**Comment by kjkazinski** [comment]
I use a link named server.jar to the non-vanilla servers.  Using this method I have not had any issues with msm starting the server.
Kadah is correct.  I normally start the server the first time via a command line to make sure everything starts correctly.
Also, did you accept the EULA?  MSM checks that.

**Comment by insuusvenerati** [comment]
Dunno if you are still having this issue but I got a forge server up and running pretty easily. I do have experience with this stuff so "easily" is relative in this case. 

What I had to do was go to files.minecraftforge.net and get the link for Universal jar by clicking the little (i) and copying the link for the Direct Download. Do sudo msm jargroup create <groupname> <url for direct download> 

Now because forge requires libraries and also uses the minecraft_server.jar you have to create a folder on your local machine and download the forge installer from files.minecraft.net. Should be the one named Installer. Run that file and select Install Server. Point it to a folder on your desktop or somewhere and hit ok. It downloads the libraries and the minecraft_server.jar. Now here's where it gets tricky. You need to upload the libraries folder and the minecraft_server.jar to the /opt/msm/jars/<jargroup> folder you created for the forge jargroup earlier. You'll probably need root access for this but I won't go into detail on how to SFTP into your server suffice to say you'll also need to edit the owner and permissions of the libraries folder and the mincraft_server.jar file to be the user you created when setting up msm.

Once that's done you're pretty much finished. Just make sure to add the version in the server.properties and sudo msm <servername> worlds load to symlink the world. After first run, accept the eula and start uploading mods to the mods folder in /opt/msm/servers/<servername>.

Hope this helps.
