### ISSUE TITLE
Server not started at system startup

### ISSUE THREAD

**Issue by gsimmons** [msmhq/msm#340]
I'm running MSM on an Amazon EC2 small instance. It runs great once I start the server, but doesn't automatically start when the instance starts up. After the instance starts up, I ssh in and do "msm start" and everything is great. I'd just prefer not to have to do that step. I'm kind of a linux newb, so I'm not sure what command to add to what config file.

Glen

**Comment by cptskyhawk** [comment]
Strange -- I just looked at my install of msm on my server, and I haven't done any customization to make my minecraft servers start automatically when the linux server boots... 

To quickly hack it so that it'll automatically start your servers when you start/restart the linux server, add the following line to your cron:

`@reboot /etc/init.d/msm start`

**Comment by endofcake** [comment]
No updates since May, I believe this is resolved.
