### ISSUE TITLE
Support Arch Linux

### ISSUE THREAD

**Issue by XtremeHacker** [msmhq/msm#354]
I'm wanting to use Arch Linux for my Minecraft server box, however it doesn't seem to be available on Arch linux, is there a way I can compile it on Arch, or is there a chance of arch becoming a supported platform?

**Comment by morbeo** [comment]
Is the problem that you can't run Minecraft on Arch or that you cannot run MSM?

Minecraft is a Java app that can be run on Archlinux easily. [This link I found on the Internet might help you](https://wiki.archlinux.org/index.php/minecraft)

MSM is a bash script that is a wrapper for Minecraft server management. It should be able to run on Arch or any other distro with bash support and provided you can run Minecraft servers (see above).

Neither of those needs compilation.

So in order to assist you we need more information. What exactly are you trying to run and what is the error you get?

**Comment by XtremeHacker** [comment]
Sorry, I think I mis-understood what MSM is, thanks for the help.
P.S. Mind closing this?

**Comment by morbeo** [comment]
You can close the issue by yourself as you have opened it.
I am afraid I do not have such privileges.
