### ISSUE TITLE
Different servers need different java versions.  How to configure msm

### ISSUE THREAD

**Issue by grtyvr** [msmhq/msm#415]
I am trying to run a mod that is only available on Forge 1.12.2 and that version of Forge needs Java 8.  The rest of my servers are fine with the latest java.  How do I configure msm to use a different version of java for a server?

**Comment by renderorange** [comment]
Each server can have its own invocation line, set in the `server.properties` file for that server.

https://msmhq.com/docs/configuration/server.html

(this is untested, but is the general idea)
```
/opt/msm/servers/test/server.properties
(... other settings)
msm-invocation=/path/to/java8 -Xms{RAM}M -Xmx{RAM}M -jar {JAR} nogui
```
If you have multiple java versions on your server, update the path to run that java instead of the default invocation for that one server.

**Comment by grtyvr** [comment]
Perfect!  Thank you.  And it is working for me.
