### ISSUE TITLE
Updated server to 1.17, won't start

### ISSUE THREAD

**Issue by wilhelmsturmer** [msmhq/msm#421]
I downloaded the 1.17 jar file, pointed the existing server to it, but each time I attempt to start the server it fails. I'm not seeing errors being generated in logs either. Please assist.

**Comment by marsn3** [comment]
It could be that you're not using java 16, as that is what Minecraft requires since 1.17. If you don't have it installed, you can try installing it using `sudo apt install openjdk-16-jre`. You might also have to select it as the default Java version by using `sudo update-alternatives --config java`.

**Comment by wilhelmsturmer** [comment]
> It could be that you're not using java 16, as that is what Minecraft requires since 1.17. If you don't have it installed, you can try installing it using `sudo apt install openjdk-16-jre`. You might also have to select it as the default Java version by using `sudo update-alternatives --config java`.

Thank you very much, this fixed my issue!
